# Generated by Django 4.2 on 2023-04-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Unassigned', max_length=50),
        ),
    ]
