# Generated by Django 4.2 on 2023-04-16 11:13

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import missions.models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_description_alter_mission_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=104)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={
                                    'user__groups__name': 'ISS_Admin_User'}, on_delete=django.db.models.deletion.CASCADE, to='missions.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
