# Generated by Django 4.2 on 2023-04-16 11:22

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_employee_social_security_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='social_security_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=9)),
        ),
    ]
