# Generated by Django 4.2 on 2023-04-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_employee_social_security_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
